musicsearch/app/urls.py
from unicodedata import name
from django.urls import path,include
from django.urls.resolvers import URLPattern
from app import views
from django.contrib.auth import views as auth_views
# from django.contrib.auth.views import logout
# from django.views.generic.base import TemplateView
# from django.contrib.auth.decorators import login_required
# from accounts import views as accounts_views


app_name='app'

urlpatterns=[
    path('',views.IndexView.as_view(),name='index'),
    # path('home/',views.IndexView.as_view(),name='index'),
    path('detail/<str:id>',views.DetailView.as_view(),name='detail'),
    # path("", auth_views.LoginView.as_view(template_name="app/templates/login.html"), name="login"),
    path("login/", auth_views.LoginView.as_view(template_name="app/templates/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(template_name="app/templates/logout.html"), name="logout"),
    path('signup/', views.signup,name = 'signup'),
    path('profile/', views.profile,name = 'profile'),
    path('password_change/',auth_views.PasswordChangeView.as_view(),name='password_change'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='passwprd_change_done'),
]

musicsearch/musicsearch/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]

musicsearch/app/models.py
from django.db import models

# Create your models here.

musicsearch/app/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm 


class SearchForm(forms.Form):
    title = forms.CharField(label='タイトル',max_length=200,required=True)



# class LoginForm(AuthenticationForm):
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         for field in self.fields.values():
#             field.widget.attrs['class'] = 'form-control'
#             field.widget.attrs['placeholder'] = field.label   

musicsearch/app/views.py
from django.shortcuts import render,redirect
from typing import ValuesView
from django.views.generic import View
import requests
import json
from .forms import SearchForm
from spotipy.oauth2 import SpotifyOAuth
from requests import Request
#signup
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth import login
# from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
# from django.views.generic import TemplateView
# from .forms import LoginForm 

import spotipy
from spotipy.oauth2 import SpotifyClientCredentials




    
# Create your views here.
class IndexView(View):
    def get(self,request, *args, **kwargs):
        form = SearchForm(request.POST or None)
   
        
        return render(request,'app/templates/index.html',{
            'form':form
        })

    def post(self, request, *args, **kwargs):
        form = SearchForm(request.POST or None)

        if form.is_valid():
            keyword = form.cleaned_data['title']
        

            list_data=[]
            sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(client_id='03a512ca71f74669a24764115e63c074',client_secret='a6d09a0987c74e5fa9380d34a106fbe7'))
            results = sp.search(q=keyword,limit=25)
            for result in results['tracks']['items']:
                title = result['name']
                id = result['id']
                popularity = result['popularity']
                image = result['album']['images'][1]['url']
                artist_name = result['album']['artists'][0]['name']

                
                
                """
                artist = sp.search(q=id,type='artist')
                artist_id = artist['artists']['items']
                artist_name=sp.artist(artist_id)
                """
                query = {
                    'title':title,
                    'id':id,
                    'popularity':popularity,
                    'image':image,
                    'artist_name':artist_name
                }
                

                list_data.append(query)
                
    
        

            return render(request,'app/templates/list.html',{
                'list_data':list_data,
                'keyword':keyword
            })

        return render(request, 'app/templates/index.html',{
            'form':form
        })
   
        
class DetailView(View):
    def get(self,request,*args,**kwargs):
        id = self.kwargs['id']
        print(id)
        sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(client_id='03a512ca71f74669a24764115e63c074',client_secret='a6d09a0987c74e5fa9380d34a106fbe7'))
        
        detail_data = []
        
        track = sp.track(id)
        title = track['name']
        popularity = track['popularity']
        image = track['album']['images'][1]['url']
        artist_name = track['album']['artists'][0]['name']
        # release = track['release_date']

    
        query = {
                'title':title,
                'id':id,
                'popularity':popularity,
                'image':image,
                'artist_name':artist_name,
                # 'release':release
            }
        detail_data.append(query)
        # print(detail_data)

        return render(request,'app/templates/detail.html',{
            'detail_data':detail_data
        })


#サインアップ
def signup(request):
    if request.method == 'POST':
        forms = UserCreationForm(request.POST)
        if forms.is_valid():
            user = forms.save()
            login(request, user)
            return render(request,'app/templates/profile.html')
    else:
        forms = UserCreationForm()
    return render(request, 'app/templates/signup.html', {'forms': forms})

def profile(request):
    return render(request,'app/templates/profile.html')

musicsearch/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script type="text/javascript" src="{% static 'js/footerfixed.js' %}"></script> 
    <title>曲検索</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a href="/" class="navbar-brand">MusicSearch</a>

         
            {% if user.is_authenticated %}
            <li>
                <a href = "{% url 'app:profile' %}"" class="nav-link">
                    ユーザ名：{{ user.get_username }}
                </a>
            </li>    
            <a href="{% url 'app:logout' %}">ログアウト</a>
            {% else %}
            <a href="{% url 'app:login' %}"">ログイン</a>
            {% endif %}
        </div>

    </nav>

    <main>
        <div class="container">
            {% block content %}
            {% endblock %}

        </div>
    </main>

    <footer class="py-2 bg-dark" id="footer">
        <p class="m-0 text-center text-white">Copyright &copy; Nao</p>
    </footer>

    {% block extra_js %}
    {% endblock %}
</body>
</html>

musicsearch/app/templates/detail.html
{% extends 'app/templates/base.html' %}
{% load static %}
{% block content %}
    
        <div class="row">
            {% for detail in detail_data %}
            <div class="col-md-6 text-center">
                <img src="{{detail.image}}" alt="" class="img-fluid">
            </div>
            
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body px-2 py-1">
                        <div class="p-4">
                            <h3>{{ detail.title }}</h3>
                            <p class="mb-3">{{ detail.artist_name }}</p>
                            
                        </div>
                        <!-- <div class="p-4">
                            <h3>{{ detail.release }}</h3>
                            <p class="mb-3">{{ detail.artist_name }}</p>
                        </div> -->
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    
{% endblock %}

musicsearch/app/templates/index.html
{% extends 'app/templates/base.html' %}
{% load widget_tweaks %}


{% block content %}
<div class="text-center my-5">
    <form action="" method="post">
        {% csrf_token %}
        <div class="align-items-center">
            {% render_field form.title name='search' class="form-control" placeholder='キーワードを入力' %}
            <button class="btn btn-primary mt-2" type="submit">検索</button>
        </div>
    </form>
</div>
{% endblock %}

musicsearch/app/templates/list.html
{% extends 'app/templates/base.html' %}

{% block content %}

<div class="text-center my-5">
    <div class="mb-5">
        <h3>「{{ keyword }}」の検索結果</h3>
    </div>
    <div class="row">
        {% for data in list_data %}
        <div class="col-3 mb-3">
            <div class="card img-thumbnail list h-100">
                <img src={{data.image}} alt="" class="card-img-top card-thum">
                <div class="card-body text-cemter px-2 py-3">
                    <h5 class="font-weigh-bold">{{ data.title }}</h5>
                    <h6>popularity{{ data.popularity }}</h6>
                    <h6>{{ data.artist_name }}</h6>
                    
                </div>
                <a href="{% url 'app:detail' data.id %}" class="stretched-link"></a>
            </div>
        </div>
        {% empty %}
            <p>該当するものはありません。</p>
        {% endfor %}
    </div>
</div>

{% endblock %}

musicsearch/app/templates/login.html
{% extends 'app/templates/base.html' %}

{% block content %}

{% if form.errors %}
<p>名前とパスワードが一致しません。正しく入力してください。</p>
{% endif %}

{% if next %}
{% if user.is_authenticated %}
  <p>アクセスしようとしたページを表示する権限がありません。 表示するためには、
    アクセス権限のあるアカウントでログインしてください。</p>
{% else %}
  <p>このページを見るためにはログインしてください。</p>
{% endif %}
{% endif %}

<form method="POST" action="{% url 'app:login' %}">
{% csrf_token %}
<table>
  <tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
  </tr>
  <tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
  </tr>
</table>

<input type="submit" value="ログイン">
<input type="hidden" name="next" value="{{ next }}">
</form>

<p><a href="{% url 'app:signup' %}">新規登録</a></p>



{% endblock %}

musicsearch/app/templates/logout.html
{% extends "app/templates/base.html" %}
{% block content %}
  <p>ログアウトしました。</p>
  <p><a href="{% url 'app:login' %}">再ログインする。</a></p>
{% endblock %}

musicsearch/app/templates/profile.html
{% extends "app/templates/base.html" %}
{% block title %}プロファイル{% endblock %}

{% block content %}
  <p>プロフィール</p>
  <p>hello {{ request.user.username }}</p>

{% endblock %}

musicsearch/app/templates/signup.html
{% extends 'app/templates/base.html' %}
{% block content %}
<main>


{# signup処理部分 #}
<form method="POST" action="{% url 'app:signup' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ forms.username.label_tag }}</td>
    <td>{{ forms.username }}</td>
</tr>
<tr>
    <td>{{ forms.email.label_tag }}</td>
    <td>{{ forms.email }}</td>
</tr>
<tr>
    <td>{{ forms.password1.label_tag }}</td>
    <td>{{ forms.password1 }}</td>
</tr>
<tr>
    <td>{{ forms.password2.label_tag }}</td>
    <td>{{ forms.password2 }}</td>
</tr>
</table>

<input type="submit" value="ログイン"">

{# エラーメッセージを表示 #}
{% if forms.errors %}
    {% for field in forms %}
        {% for error in field.errors %}
            <p>{{ error }}</p>
        {% endfor %}
     {% endfor %}
{% endif %} 
</form>
{% endblock %}